version: '3'

services:
  dockerdemo:
    image: dockerdemo
    build:
      context: .
      dockerfile: DockerDemo/Dockerfile
    networks:
      - appnet
  redis:
    image: redis:latest
    networks:
      - appnet
networks:
  appnet: